/**
 * GET /api/mcp/themes/[id]/css — 테마 CSS 변수 생성 API
 * [SPEC-MCP-007:E-006] fetchCSSVariables(themeId) 지원
 * @framingui/core의 loadTheme + oklchToCSS를 사용해 CSS 문자열 생성
 */

import { NextRequest, NextResponse } from 'next/server';
import { loadTheme, oklchToCSS } from '@framingui/core';
import { authenticateMcpRequest } from '@/lib/mcp/auth-helper';

const MASTER_EMAILS = ['soo.kate.yeon@gmail.com'];

/**
 * ThemeV2에서 CSS Variables 문자열 생성
 */
function generateCSSFromTheme(theme: any): string {
  const lines: string[] = [
    `/* Generated by Framingui - Theme: ${theme.id} */`,
    `/* Schema Version: ${theme.schemaVersion} */`,
    '',
    ':root {',
  ];

  // Layer 1: Atomic Tokens
  lines.push('  /* === Layer 1: Atomic Tokens === */');
  const { color } = theme.tokens.atomic;
  if (color.brand) {
    for (const [shade, oklch] of Object.entries(color.brand)) {
      lines.push(`  --color-brand-${shade}: ${oklchToCSS(oklch as any)};`);
    }
  }
  if (color.neutral) {
    for (const [shade, oklch] of Object.entries(color.neutral)) {
      lines.push(`  --color-neutral-${shade}: ${oklchToCSS(oklch as any)};`);
    }
  }
  if (color.accent) {
    for (const [shade, oklch] of Object.entries(color.accent)) {
      lines.push(`  --color-accent-${shade}: ${oklchToCSS(oklch as any)};`);
    }
  }
  if (color.success) {
    lines.push(`  --color-success: ${oklchToCSS(color.success)};`);
  }
  if (color.warning) {
    lines.push(`  --color-warning: ${oklchToCSS(color.warning)};`);
  }
  if (color.error) {
    lines.push(`  --color-error: ${oklchToCSS(color.error)};`);
  }
  if (color.info) {
    lines.push(`  --color-info: ${oklchToCSS(color.info)};`);
  }

  lines.push('');
  for (const [size, value] of Object.entries(theme.tokens.atomic.spacing)) {
    lines.push(`  --spacing-${size}: ${value};`);
  }
  lines.push('');
  for (const [size, value] of Object.entries(theme.tokens.atomic.radius)) {
    lines.push(`  --radius-${size}: ${value};`);
  }

  // Typography
  lines.push('');
  lines.push('  /* === Typography === */');
  const { typography } = theme;
  if (typography.fontFamily) {
    for (const [name, value] of Object.entries(typography.fontFamily)) {
      lines.push(`  --font-family-${name}: ${value};`);
    }
  }
  if (typography.fontSize) {
    for (const [name, value] of Object.entries(typography.fontSize)) {
      lines.push(`  --font-size-${name}: ${value};`);
    }
  }
  if (typography.fontWeight) {
    for (const [name, value] of Object.entries(typography.fontWeight)) {
      lines.push(`  --font-weight-${name}: ${value};`);
    }
  }
  if (typography.lineHeight) {
    for (const [name, value] of Object.entries(typography.lineHeight)) {
      lines.push(`  --line-height-${name}: ${value};`);
    }
  }
  if (typography.letterSpacing) {
    for (const [name, value] of Object.entries(typography.letterSpacing)) {
      lines.push(`  --letter-spacing-${name}: ${value};`);
    }
  }

  // Border
  lines.push('');
  lines.push('  /* === Border === */');
  const { border } = theme;
  if (border.width) {
    for (const [name, value] of Object.entries(border.width)) {
      lines.push(`  --border-width-${name}: ${value};`);
    }
  }
  if (border.radius) {
    for (const [name, value] of Object.entries(border.radius)) {
      lines.push(`  --border-radius-${name}: ${value};`);
    }
  }

  // Elevation
  lines.push('');
  lines.push('  /* === Elevation === */');
  const { elevation } = theme;
  if (elevation.level) {
    for (const [name, value] of Object.entries(elevation.level)) {
      lines.push(`  --elevation-${name}: ${value};`);
    }
  }

  // Motion
  lines.push('');
  lines.push('  /* === Motion === */');
  const { motion } = theme;
  if (motion.duration) {
    for (const [name, value] of Object.entries(motion.duration)) {
      lines.push(`  --duration-${name}: ${value};`);
    }
  }
  if (motion.easing) {
    for (const [name, value] of Object.entries(motion.easing)) {
      lines.push(`  --easing-${name}: ${value};`);
    }
  }

  // State Layer
  lines.push('');
  lines.push('  /* === State Layer === */');
  const { stateLayer } = theme;
  if (stateLayer.hover?.opacity !== undefined) {
    lines.push(`  --state-hover-opacity: ${stateLayer.hover.opacity};`);
  }
  if (stateLayer.pressed?.opacity !== undefined) {
    lines.push(`  --state-pressed-opacity: ${stateLayer.pressed.opacity};`);
  }
  if (stateLayer.focus?.opacity !== undefined) {
    lines.push(`  --state-focus-opacity: ${stateLayer.focus.opacity};`);
  }
  if (stateLayer.disabled?.opacity !== undefined) {
    lines.push(`  --state-disabled-opacity: ${stateLayer.disabled.opacity};`);
  }

  // Layer 2: Semantic Tokens
  lines.push('');
  lines.push('  /* === Layer 2: Semantic Tokens === */');
  const { semantic } = theme.tokens;
  if (semantic.background) {
    if (semantic.background.canvas) {
      lines.push(`  --bg-canvas: ${semantic.background.canvas};`);
    }
    if (semantic.background.surface) {
      for (const [name, value] of Object.entries(semantic.background.surface)) {
        lines.push(`  --bg-surface-${name}: ${value};`);
      }
    }
    if (semantic.background.elevated) {
      for (const [name, value] of Object.entries(semantic.background.elevated)) {
        lines.push(`  --bg-elevated-${name}: ${value};`);
      }
    }
  }
  if (semantic.foreground) {
    if (semantic.foreground.primary) {
      for (const [name, value] of Object.entries(semantic.foreground.primary)) {
        lines.push(`  --fg-primary-${name}: ${value};`);
      }
    }
    if (semantic.foreground.secondary) {
      for (const [name, value] of Object.entries(semantic.foreground.secondary)) {
        lines.push(`  --fg-secondary-${name}: ${value};`);
      }
    }
    if (semantic.foreground.disabled) {
      lines.push(`  --fg-disabled: ${semantic.foreground.disabled};`);
    }
    if (semantic.foreground.placeholder) {
      lines.push(`  --fg-placeholder: ${semantic.foreground.placeholder};`);
    }
  }
  if (semantic.border) {
    if (semantic.border.default) {
      for (const [name, value] of Object.entries(semantic.border.default)) {
        lines.push(`  --border-${name}: ${value};`);
      }
    }
    if (semantic.border.focus) {
      lines.push(`  --border-focus: ${semantic.border.focus};`);
    }
    if (semantic.border.error) {
      lines.push(`  --border-error: ${semantic.border.error};`);
    }
    if (semantic.border.success) {
      lines.push(`  --border-success: ${semantic.border.success};`);
    }
  }

  lines.push('}');

  // Dark Mode
  if (theme.darkMode?.tokens?.semantic) {
    lines.push('');
    lines.push('.dark {');
    lines.push('  /* === Dark Mode Overrides === */');
    const darkSemantic = theme.darkMode.tokens.semantic;
    if (darkSemantic.background?.canvas) {
      lines.push(`  --bg-canvas: ${darkSemantic.background.canvas};`);
    }
    if (darkSemantic.background?.surface) {
      for (const [name, value] of Object.entries(darkSemantic.background.surface)) {
        lines.push(`  --bg-surface-${name}: ${value};`);
      }
    }
    lines.push('}');
  }

  return lines.join('\n');
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const auth = await authenticateMcpRequest(request);
    if (!auth.valid) {
      return auth.response;
    }

    const { id: themeId } = await params;

    // 라이선스 확인
    const isMaster = MASTER_EMAILS.includes(auth.email.toLowerCase());
    if (!isMaster && !auth.licensedThemes.includes(themeId)) {
      return NextResponse.json(
        { success: false, error: `Theme "${themeId}" is not included in your license.` },
        { status: 403 }
      );
    }

    const theme = loadTheme(themeId);
    if (!theme) {
      return NextResponse.json(
        { success: false, error: `Theme "${themeId}" not found.` },
        { status: 404 }
      );
    }

    const css = generateCSSFromTheme(theme);

    return NextResponse.json(
      { success: true, css },
      {
        status: 200,
        headers: {
          'Cache-Control': 'public, s-maxage=3600',
          ...auth.rateLimitHeaders,
        },
      }
    );
  } catch (error) {
    console.error('[MCP Theme CSS] Unexpected error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Max-Age': '86400',
    },
  });
}
