#!/bin/bash

# PR 자동 수정 스크립트
# CI/CD 실패 시 자동으로 로그를 분석하고 수정을 시도합니다.

set -e

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 로그 함수
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# PR 체크 상태 확인
log_info "Checking PR status..."
if ! gh pr checks > /dev/null 2>&1; then
    log_error "No PR found for current branch. Please create a PR first."
    exit 1
fi

# PR 체크 결과 표시
gh pr checks

# 실패한 체크 개수 확인
FAILED_CHECKS=$(gh pr checks --json conclusion --jq '[.[] | select(.conclusion == "failure")] | length')

if [ "$FAILED_CHECKS" -eq 0 ]; then
    log_success "All checks passed! No fixes needed."
    exit 0
fi

log_warning "Found $FAILED_CHECKS failed check(s). Attempting auto-fix..."

# 최근 워크플로우 실행 ID 가져오기
log_info "Fetching workflow run logs..."
RUN_ID=$(gh run list --limit 1 --json databaseId --jq '.[0].databaseId')

if [ -z "$RUN_ID" ]; then
    log_error "Could not find workflow run ID"
    exit 1
fi

# 로그 파일 생성
LOG_FILE="ci_logs_$(date +%Y%m%d_%H%M%S).txt"
gh run view "$RUN_ID" --log > "$LOG_FILE" 2>&1 || true

log_info "Logs saved to: $LOG_FILE"
log_info "Analyzing logs for common issues..."

# 변경사항 플래그
CHANGES_MADE=false
AUTO_FIXES_APPLIED=()
REPORT_ONLY_FINDINGS=()
FILES_TO_STAGE=()

# 1. Lockfile 드리프트 확인 및 수정
if grep -qi "ERR_PNPM_OUTDATED_LOCKFILE" "$LOG_FILE"; then
    log_info "Lockfile drift detected. Refreshing pnpm lockfile..."
    if pnpm install --lockfile-only; then
        CHANGES_MADE=true
        AUTO_FIXES_APPLIED+=("Updated pnpm-lock.yaml for frozen lockfile drift")
    else
        log_error "Lockfile refresh failed. Manual review required."
        REPORT_ONLY_FINDINGS+=("Lockfile drift detected but pnpm install --lockfile-only failed")
    fi
fi

# 2. 린트 오류 확인 및 수정
if grep -Eqi "eslint|lint" "$LOG_FILE"; then
    log_info "ESLint errors detected. Running lint:all..."
    if pnpm lint:all 2>&1 | tee lint_output.txt; then
        log_success "Linting passed"
    else
        log_warning "Linting failed, attempting auto-fix..."
        # 각 패키지별로 lint:fix 실행
        pnpm --filter "./packages/*" exec eslint --fix "src/**/*.{ts,tsx}" "__tests__/**/*.{ts,tsx}" || true
        CHANGES_MADE=true
        AUTO_FIXES_APPLIED+=("Applied ESLint safe autofixes")
    fi
    rm -f lint_output.txt
fi

# 3. 포맷팅 오류 확인 및 수정
if grep -Eqi "prettier|format" "$LOG_FILE"; then
    log_info "Formatting issues detected. Running prettier..."
    pnpm exec prettier --write "packages/*/src/**/*.{ts,tsx}" "packages/*/__tests__/**/*.{ts,tsx}" "*.{ts,js,json}" ".github/**/*.yml" || true
    CHANGES_MADE=true
    AUTO_FIXES_APPLIED+=("Applied Prettier formatting updates")
fi

# 4. TypeScript 타입 체크 (리포트 전용)
if grep -Eqi "typescript|tsc|type error|TS[0-9]{4}" "$LOG_FILE"; then
    log_warning "TypeScript errors detected. Collecting report only..."
    if pnpm typecheck 2>&1 | tee typecheck_output.txt; then
        log_success "Type check passed"
    else
        log_error "Type errors found. Report only; no automatic edits will be applied:"
        tail -n 20 typecheck_output.txt
        REPORT_ONLY_FINDINGS+=("TypeScript/type-check failure requires manual code changes")
    fi
    rm -f typecheck_output.txt
fi

# 5. 테스트 실패 확인 (리포트 전용)
if grep -Eqi "test.*failed|vitest.*fail|jest|playwright|e2e" "$LOG_FILE"; then
    log_warning "Test failures detected. Collecting report only..."
    if pnpm ci:test 2>&1 | tee test_output.txt; then
        log_success "Tests passed"
    else
        log_error "Tests failed. Report only; no automatic edits will be applied:"
        tail -n 30 test_output.txt
        REPORT_ONLY_FINDINGS+=("Test failure requires investigation and manual fixes")
    fi
    rm -f test_output.txt
fi

# 6. 빌드 오류 확인 (리포트 전용)
if grep -Eqi "build.*failed|build error|rollup|tsup|vite build" "$LOG_FILE"; then
    log_warning "Build errors detected. Collecting report only..."
    if pnpm build:all 2>&1 | tee build_output.txt; then
        log_success "Build passed"
    else
        log_error "Build failed. Report only; no automatic edits will be applied:"
        tail -n 30 build_output.txt
        REPORT_ONLY_FINDINGS+=("Build failure requires investigation and manual fixes")
    fi
    rm -f build_output.txt
fi

# 변경사항이 있으면 커밋 및 푸시
if [ "$CHANGES_MADE" = true ]; then
    while IFS= read -r file; do
        [ -n "$file" ] && FILES_TO_STAGE+=("$file")
    done < <(git ls-files -m -- pnpm-lock.yaml packages .github "*.ts" "*.js" "*.json" "*.yml" "*.yaml")
fi

if [ "$CHANGES_MADE" = true ] && [ "${#FILES_TO_STAGE[@]}" -gt 0 ]; then
    log_info "Changes detected. Committing fixes..."
    
    git add -- "${FILES_TO_STAGE[@]}"
    
    # 커밋 메시지 생성
    AUTO_FIX_SUMMARY=$(printf -- '- %s\n' "${AUTO_FIXES_APPLIED[@]}")
    COMMIT_MSG="chore: auto-fix CI/CD failures

Auto-fixes applied:
$AUTO_FIX_SUMMARY

Generated by auto-fix-pr.sh
Workflow run: https://github.com/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/$RUN_ID"
    
    git commit -m "$COMMIT_MSG"
    
    log_info "Pushing changes..."
    git push
    
    log_success "Fixes committed and pushed!"
    log_info "Waiting for CI/CD to re-run (60 seconds)..."
    sleep 60
    
    log_info "Checking PR status again..."
    gh pr checks
    
    # 다시 실패 체크
    NEW_FAILED_CHECKS=$(gh pr checks --json conclusion --jq '[.[] | select(.conclusion == "failure")] | length')
    
    if [ "$NEW_FAILED_CHECKS" -eq 0 ]; then
        log_success "All checks now passing! 🎉"
    else
        log_warning "$NEW_FAILED_CHECKS check(s) still failing. Manual intervention may be required."
        log_info "Check the PR for details: $(gh pr view --json url -q .url)"
    fi
else
    log_warning "No safe automatic fixes available or no changes detected."
    log_info "Manual intervention required. Check the logs at: $LOG_FILE"
    log_info "PR URL: $(gh pr view --json url -q .url)"
fi

if [ "${#REPORT_ONLY_FINDINGS[@]}" -gt 0 ]; then
    log_info "Report-only findings:"
    printf '%s\n' "${REPORT_ONLY_FINDINGS[@]}"
fi

# 로그 파일 정리 (선택사항)
log_info "Keeping log file for review: $LOG_FILE"
log_info "To delete it, run: rm $LOG_FILE"
